### ISSUE TITLE
关于查歌api的问题

### ISSUE THREAD

**Issue by aaaa794191505** [Diving-Fish/mai-bot#13]
我仿照b40功能想写一个查询某账号某定级所有歌曲的功能，用的是query/plate接口，发现总是返回500错误。
以下是maimai_best_40.py文件中仿照b40的方法接口：
```
async def generate_all(payload: Dict) -> (Optional[Image.Image], BestList, bool):
    async with aiohttp.request("POST", "https://www.diving-fish.com/api/maimaidxprober/query/plate",
                               json=payload) as resp:
        # print(resp)
        print(await resp.text())
```
以下是maimaidx中的调用语句：
```
qvtest = on_command("test")


@qvtest.handle()
async def _(bot: Bot, event: Event, state: T_State):
    username = str(event.get_message()).strip()
    p = ""
    if username == "":
        p = {'qq': str(event.get_user_id())}
    else:
        p = {'username': username}
    print(p)
    img, t_list, success = await generate_all(p)
```
输出如下：
```
<!doctype html>
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
Server got itself in trouble
```
想问下是我链接写错了嘛还是参数不对，烦请df大佬能给予解答，要是不方便或者不允许调用或者其他原因的话还请告知一下，谢谢啦~顺便，您好强，代码都好简洁ww

**Comment by Diving-Fish** [comment]
这个参数是调query/player的。如果要调query/plate的话，参数应该像这样
```
{
    "username": "DivingFish",
    "version": ["maimai", "maimai MiLK"]
}
```

**Comment by aaaa794191505** [comment]
> 这个参数是调query/player的。如果要调query/plate的话，参数应该像这样
> 
> ```
> {
>     "username": "DivingFish",
>     "version": ["maimai", "maimai MiLK"]
> }
> ```

谢谢!想问下这个版本如果要查询所有版本的话是要把所有版本都列上去嘛

**Comment by aaaa794191505** [comment]
> 这个参数是调查询/玩家的。如果要调查询/盘子的话，参数应该像这样
> 
> ```
> {
>     "username": "DivingFish",
>     "version": ["maimai", "maimai MiLK"]
> }
> ```
对了，再反馈给您一个bug，查分器网站里，之前编辑过个人资料的再编辑不会报错，但是之前没编辑过的新用户编辑完点击保存会没反应，点击保存后报这样的错。 还挺久了，谢谢
![捕获](https://user-images.githubusercontent.com/55777146/142135753-b08d46e2-a864-4292-87d4-19edd3902e97.PNG)
