### ISSUE TITLE
`/src/static` 中文件的授权协议

### ISSUE THREAD

**Issue by DrLee-lihr** [Diving-Fish/mai-bot#20]
如题，资源文件中授权协议没有指明，是用 MIT 进行分发吗？但 SEGA 版权下的曲绘和资源文件用 MIT 是否有点不太妥当（
另外 aliases.csv 我想将它用到我的一个项目里（随npm包进行分发，协议 Apache-2.0），不知道是否可以（

**Comment by Diving-Fish** [comment]
static.zip 里面的资源仅供学习交流使用，请自觉在下载24小时内删除（
> 另外 aliases.csv 我想将它用到我的一个项目里（随npm包进行分发，协议 Apache-2.0），不知道是否可以（
这个貌似已经有人维护别的别名api接口了

**Comment by DrLee-lihr** [comment]
> static.zip 里面的资源仅供学习交流使用，请自觉在下载24小时内删除（
> 
> > 另外 aliases.csv 我想将它用到我的一个项目里（随npm包进行分发，协议 Apache-2.0），不知道是否可以（
> > 这个貌似已经有人维护别的别名api接口了

草（
但是接口貌似不是很稳定（我也看到了，目前在用），有时会出问题，想多个获取方式
如果 aliases.csv 不方便分发就算了（）

**Comment by Diving-Fish** [comment]
没关系，可以分发。只是这个文件里面的别名已经很久没更新了，时效性可能不如接口
