### ISSUE TITLE
图片资源打不开？

### ISSUE THREAD

**Issue by xyseer** [Diving-Fish/mai-bot#25]
![截屏2022-08-02 22 46 34](https://user-images.githubusercontent.com/25876240/182403592-d2252c49-d034-4763-af78-e53d745d2485.png)
b40时似乎发生了图片资源打不开的问题

**Comment by notpeople249** [comment]
#11 
这边已经回复了，需要先下载并放入一个文件夹才行，并却确保文件夹路径不变
