### ISSUE TITLE
运行bot.py的时候报错了怎么办呀qwq

### ISSUE THREAD

**Issue by kiyomiOvO** [Diving-Fish/mai-bot#27]
Traceback (most recent call last):
  File "C:\Users\nanaQaQ\Desktop\mai-bot\bot.py", line 5, in <module>
    import nonebot
ModuleNotFoundError: No module named 'nonebot'

**Comment by Rouphy** [comment]
建议回去仔细阅读readme文件，你这个是缺模组，安装requirements的时候报错没仔细看吧😅

**Comment by kiyomiOvO** [comment]
> 

那安装requirements报错怎么解决呀qwq

**Comment by Rouphy** [comment]
> 

回去仔细看README的配置nonebot和cq-http报错，按照提示文档操作之后再试，如果还不行就用pycharm之类的IDLE导入工程查看缺少哪个模块自己手动用pip安装

**Comment by kiyomiOvO** [comment]
> > 
> 
> 回去仔细看README的配置nonebot和cq-http报错，按照提示文档操作之后再试，如果还不行就用pycharm之类的IDLE导入工程查看缺少哪个模块自己手动用pip安装

俺解决了 py版本太高了，我换了3.8的版本就可以了
