### ISSUE TITLE
boy.py运行报错

### ISSUE THREAD

**Issue by MC57348** [Diving-Fish/mai-bot#29]
今天运行bot的时候发现bot.py无法正常运行，提示以一种访问权限不允许的方式做了一个访问套接字的尝试。
怀疑是启动bot的同时进行查分器成绩上传导致冲突
//运行报错log
============== RESTART: C:\Users\38369\Desktop\mai-bot-main\bot.py =============
[32m08-16 23:27:26[0m [[1mINFO[0m] [36m[4mnonebot[0m[36m[0m | NoneBot is initializing...
[32m08-16 23:27:26[0m [[1mINFO[0m] [36m[4mnonebot[0m[36m[0m | Current [33m[1mEnv: prod[0m[33m[0m
[32m08-16 23:27:29[0m [[1mINFO[0m] [36m[4mnonebot[0m[36m[0m | Succeeded to import "[33mmaimaidx[0m"
[32m08-16 23:27:29[0m [[1mINFO[0m] [36m[4mnonebot[0m[36m[0m | Succeeded to import "[33mpublic[0m"
[32m08-16 23:27:29[0m [[1mINFO[0m] [36m[4mnonebot[0m[36m[0m | Running NoneBot...
[32m08-16 23:27:29[0m [[1mINFO[0m] [36m[4muvicorn[0m[36m[0m | Started server process [25428]
[32m08-16 23:27:29[0m [[1mINFO[0m] [36m[4muvicorn[0m[36m[0m | Waiting for application startup.
[32m08-16 23:27:29[0m [[1mINFO[0m] [36m[4muvicorn[0m[36m[0m | Application startup complete.
[32m08-16 23:27:29[0m [[31m[1mERROR[0m] [36m[4muvicorn[0m[36m[0m | [Errno 10013] error while attempting to bind on address ('127.0.0.1', 10219): 以一种访问权限不允许的方式做了一个访问套接字的尝试。
[32m08-16 23:27:34[0m [[1mINFO[0m] [36m[4muvicorn[0m[36m[0m | Waiting for application shutdown.
[32m08-16 23:27:34[0m [[1mINFO[0m] [36m[4muvicorn[0m[36m[0m | Application shutdown complete.

**Comment by MC57348** [comment]
[2022-08-17 01:19:40] [WARNING]: 连接到反向WebSocket Universal服务器 ws://127.0.0.1:10219/cqhttp/ws 时出现错误: dial tcp 127.0.0.1:10219: connectex: No connection could be made because the target machine actively refused it.

**Comment by MC57348** [comment]
现在甚至只有前两行了

**Comment by Diving-Fish** [comment]
端口占用了，查一下怎么找到占用对应端口的进程吧。或者直接重启解决所有问题。
