### ISSUE TITLE
websocket反向代理出现问题

### ISSUE THREAD

**Issue by cppIdiot** [Diving-Fish/mai-bot#3]
![image](https://user-images.githubusercontent.com/69411326/128623263-1d4cf35e-3469-4f25-a79e-4eec3e5979de.png)

**Comment by cppIdiot** [comment]
使用的是腾讯云服务器，防火墙策略作如下设置：
开放全部的TCP端口

**Comment by Diving-Fish** [comment]
本地网络也不需要开放tcp端口吧。lsof -i:10219看看？

**Comment by cppIdiot** [comment]
![image](https://user-images.githubusercontent.com/69411326/128865879-001909cf-cabd-4f0d-865a-813071b615cb.png)
经过您给予的这条指令之后，显示如上图。
本地并没有占用这个端口的任何进程，问题出的我也有点奇怪，按理来说应该是没问题的

**Comment by Diving-Fish** [comment]
检查一下nonebot的启动情况吧，肯定是程序本身没跑起来
