### ISSUE TITLE
【提问】是否考虑做中二b30功能？或者是否有类似的项目？

### ISSUE THREAD

**Issue by Agnes4m** [Diving-Fish/mai-bot#39]
因为api接口同时也提供了中二的信息，所以想问问是否考虑加入中二的b30功能。

如果有类似的开源项目指引，希望大佬可以提供链接让我们学习orz

**Comment by jiangyin14** [comment]
Diving-fish/Chiyuki-Bot

**Comment by Agnes4m** [comment]
> Diving-fish/Chiyuki-Bot

并没有

**Comment by jiangyin14** [comment]
> > Diving-fish/Chiyuki-Bot
> 
> 
> 
> 并没有

报一丝（）
我也不知道哪有
