### ISSUE TITLE
#在python 311可能会出现pip install问题）

### ISSUE THREAD

**Issue by Steve0807** [Diving-Fish/mai-bot#41]
昨天我朋友在pip install的时候遇到了报错，我在我的Anaconda里安装m2w64拓展后出现同样报错

> `error:Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools":https://visualstudio.microsoft.com/visual-cpp-build-tools/`

切换版本至python 310后未出现此问题

且目前貌似仅有python 311出现此问题

- 是python新手，如果是我的错误，那那那非常抱歉w））））））

Python Version截图
![python version](https://github.com/Diving-Fish/mai-bot/assets/104258961/ded1f2af-284b-4619-a59b-c8c5782deed1)

安装后截图
![After installation](https://github.com/Diving-Fish/mai-bot/assets/104258961/b95ba625-714f-4567-9000-31207a83e4ed)

**Comment by Diving-Fish** [comment]
这说的很清楚吧，缺少visual C++，装一个就行了
