### ISSUE TITLE
这个程序是否嵌入了cqhttp的相关代码

### ISSUE THREAD

**Issue by whjsdm** [Diving-Fish/mai-bot#43]
我想把这个程序应用到微信端上，但是因为没有注释我不太清楚这个有没有嵌入cqhttp的相关代码，如果有请指出有哪些是，我想要一个纯后台程序以便我后续调用这些方法以及磨合我目前所开发的代码

**Comment by Diving-Fish** [comment]
没有 纯python

**Comment by whjsdm** [comment]
好的谢谢

**Comment by whjsdm** [comment]
一个新的问题，之前使用指南中下载了资源文件，那么查分的时候bot到底是从这个资源文件中读取图片的，还是从水鱼查分器的数据库中通过爬虫获取图片

**Comment by Diving-Fish** [comment]
资源文件

**Comment by whjsdm** [comment]
那么目前大多maimai bot所输出的图片也是来自资源文件吗，如果是这样的话，那么他们是否违规了呢

**Comment by whjsdm** [comment]
换个说法，如果我的机器人生成的图片引用了资源文件中的资料，但是绝不传播出去算违规吗
