### ISSUE TITLE
鱼佬的封面api接口怎么用，封面错位频发的情况下能否靠更改代码解决

### ISSUE THREAD

**Issue by Rouphy** [Diving-Fish/mai-bot#46]
`        try:
            file = f"https://www.diving-fish.com/covers/{get_cover_len5_id(music['id'])}.png"
            await query_chart.send(Message([
                MessageSegment("text", {
                    "text": f"{music['id']}. {music['title']}\n"
                }),
                MessageSegment("image", {
                    "file": f"{file}"
                }),
                MessageSegment("text", {
                    "text": f"艺术家: {music['basic_info']['artist']}\n分类: {music['basic_info']['genre']}\nBPM: {music['basic_info']['bpm']}\n版本: {music['basic_info']['from']}\n难度: {'/'.join(music['level'])}"
                })
            ]))`
大概是这里的https://www.diving-fish.com/covers/
鱼佬能不能提供一下这个接口的使用方法呢（（（

**Comment by Rouphy** [comment]
目前的问题是b50的图片没有问题，但是单曲查询的时候图片是错误的

**Comment by Rouphy** [comment]
static包是最新的版本，各个图片的id.png也都对的上

**Comment by Diving-Fish** [comment]
删掉你bot cqhttp 里面 cache 文件夹下的所有内容 然后重启bot再试

**Comment by Rouphy** [comment]
已解决，谢谢鱼佬
