### ISSUE TITLE
安装依赖报错

### ISSUE THREAD

**Issue by HuanKongzzz** [Diving-Fish/mai-bot#49]
一开始是缺少visual studio c++安装后报错变成这样![Screenshot_20231019_174835.jpg](https://github.com/Diving-Fish/mai-bot/assets/119497994/b6cc0a89-462a-4a95-8ef5-7f8840ffd69b)

![Screenshot_20231019_174848.jpg](https://github.com/Diving-Fish/mai-bot/assets/119497994/b49a42fa-c9c4-4bb1-b9ef-c8f9dac7bb5f)

![Screenshot_20231019_174854.jpg](https://github.com/Diving-Fish/mai-bot/assets/119497994/f66b6b56-23e2-48f9-bbaf-b4f6b4316f8b)

![Screenshot_20231019_174859.jpg](https://github.com/Diving-Fish/mai-bot/assets/119497994/2ae227df-d1b3-4c57-a513-35471e8acbf5)

**Comment by HuanKongzzz** [comment]
是安装的visual studio c++版本有问题吗（

**Comment by Diving-Fish** [comment]
你的python是手动编译的吗

**Comment by HuanKongzzz** [comment]
> 你的python是手动编译的吗

不是

**Comment by Diving-Fish** [comment]
卸载python之后，重装一个3.10版本的再试试

**Comment by HuanKongzzz** [comment]
> 卸载python之后，重装一个3.10版本的再试试

感谢，问题已解决
